ARG BASE_IMG="flask"
FROM ${BASE_IMG}

ARG FLASK_C_WORKDIR="flask_server"
# Moving project and installing dependencies 
WORKDIR ${FLASK_C_WORKDIR}
COPY . .
RUN pipenv install

# CMD ["flask", "run"]

# CMD $(pipenv --venv)/bin/python -m flask run --host="0.0.0.0"
ARG FLASK_EXEC_SCRIPT="script.sh"
ENV FLASK_EXEC_SCRIPT ${FLASK_EXEC_SCRIPT}

# Copy the script
COPY ./base_n_flask.sh /base_n_flask.sh
RUN sudo chmod +x /${FLASK_EXEC_SCRIPT}
CMD /${FLASK_EXEC_SCRIPT}

