version: "3.9"

services:

  influxdb:
    build:
      dockerfile: "DockerfileInfluxdb"
      target: influx_tgt
      args:
        - INFLUX_IMG
    image: influx_img
    container_name: ${INFLUX_CONTAINER}
    stdin_open: true
    tty: true
    hostname: ${INFLUX_CONTAINER}
    environment:
      - INFLUXD_REPORTING_DISABLED=true
      - INFLUXDB_DB=${INFLUX_DB_NAME}
      - INFLUXDB_ADMIN_USER="admin"
      - INFLUXDB_ADMIN_PASSWORD="admin"
    # ports:  # Redirection is not necessary
    #   - '${INFLUX_DB_PORT}:${INFLUX_DB_PORT}'
    volumes:
      - influxdb_data:/var/lib/influxdb

  # https://grafana.com/docs/grafana/latest/setup-grafana/configure-docker/
  grafana:
    depends_on:
      - influxdb
    image: ${GRAFANA_IMG}
    container_name: ${GRAFANA_CONTAINER}
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning  # Default value, but to ensure it
    ports:
      - '${GRAFANA_PORT}:${GRAFANA_PORT}'
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning


  # For testing
  # grafana2:
  #   depends_on:
  #     - influxdb
  #   image: grafana_test
  #   container_name: grafana_prueba_cont
  #   environment:
  #    #- GF_SERVER_ROOT_URL=http://my.grafana.server/
  #    #- GF_INSTALL_PLUGINS=grafana-clock-panel
  #     - GF_PATHS_PROVISIONING=/etc/grafana/provisioning  # Default value, but to ensure ir
  #     #- GF_AUTH_DISABLE_LOGIN_FORM=true
  #     #- GF_AUTH_ANONYMOUS_ENABLED=true
  #     #- GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
  #   ports:
  #    - '3001:${GRAFANA_PORT}'
  #   volumes:
  #     - ./grafana/provisioning:/etc/grafana/provisioning

  genesis:
    depends_on:
      - influxdb
    build:
      context: .
      target: ${BASE_IMG}
      #dockerfile: ./Dockerfile
      args:
        - PROBE_FOLDER
        - C_WORKDIR
    environment:
      - INFLUX_CONTAINER
      - INFLUX_DB_PORT
      - INFLUX_DB_NAME
      - C_WORKDIR
    image: ${BASE_IMG}
    volumes:
      - ./${PROBE_FOLDER}:${C_WORKDIR}

  MServ_1:
    extends:
      service: genesis
    stdin_open: true
    tty: true
    environment:
      - SERVICE_NAMES=IMG_GEN,ASCII_ART,GRAY_SCALE
      - MICROSERVICE=Frontend
    hostname: Frontend
    container_name: Frontend

  MServ_2:
    extends:
      service: genesis
    stdin_open: true
    tty: true
    environment:
      - SERVICE_NAMES=IMG_GEN
      - MICROSERVICE=TextDescriptor
    hostname: TextDescriptor
    container_name: TextDescriptor

  MServ_3:
    extends:
      service: genesis
    stdin_open: true
    tty: true
    environment:
      - SERVICE_NAMES=IMG_GEN
      - MICROSERVICE=APICaller
    hostname: APICaller
    container_name: APICaller

  MServ_4:
    extends:
      service: genesis
    stdin_open: true
    tty: true
    environment:
      - SERVICE_NAMES=IMG_GEN,ASCII_ART,GRAY_SCALE
      - MICROSERVICE=Showdata
    hostname: Showdata
    container_name: Showdata

  MServ_5:
    extends:
      service: genesis
    stdin_open: true
    tty: true
    environment:
      - SERVICE_NAMES=ASCII_ART,GRAY_SCALE
      - MICROSERVICE=ImgUploader
    hostname: ImgUploader
    container_name: ImgUploader

  MServ_6:
    extends:
      service: genesis
    stdin_open: true
    tty: true
    environment:
      - SERVICE_NAMES=ASCII_ART
      - MICROSERVICE=ASCIIArt
    hostname: ASCIIArt
    container_name: ASCIIArt

  MServ_7:
    extends:
      service: genesis
    stdin_open: true
    tty: true
    environment:
      - SERVICE_NAMES=GRAY_SCALE
      - MICROSERVICE=GrayScale
    hostname: GrayScale
    container_name: GrayScale

  videosrv:
    extends:
      service: genesis
    build:
      target: videosrv_tgt
    image: videosrv_img
    stdin_open: true
    tty: true
    environment:
      - SERVICE_NAMES=GRAY_SCALE
      - MICROSERVICE=VideoSrv
    hostname: VideoSrv
    container_name: VideoSrv

  ffmpeg:
    extends:
      service: genesis
    depends_on:
      - videosrv
    build:
      target: ffmpeg_tgt
    image: ffmpeg_img
    stdin_open: true
    tty: true
    environment:
      - SERVICE_NAMES=GRAY_SCALE
      - MICROSERVICE=FFmpeg
    hostname: FFmpeg
    container_name: FFmpeg

volumes:
  influxdb_data:
  #grafana_data:
  