version: "3.9"

services:
  
  genesis:
    stdin_open: true 
    tty: true
    
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - PROBE_FOLDER
        - EXEC_SCRIPT
        - C_WORKDIR
    environment:
      - INFLUX_DB_MEASUREMENT
      - INFLUX_CONTAINER
      - INFLUX_DB_PORT
      - INFLUX_DB_NAME
      - SERVICE_NAME=${GRAY_SCALE_SERVICE}
    
    image: ${BASE_IMG}

    hostname: ${M_SERVICE}
    container_name: ${M_SERVICE}

    volumes:
      - ./${PROBE_FOLDER}:${C_WORKDIR}

  clone:
    extends:
      service: genesis
    environment:
      - SERVICE_NAME=${ASCIIART_SERVICE}
    
    hostname: ${M_SERVICE_2}
    container_name: ${M_SERVICE_2}


  # frontend:
  #   depends_on:
  #     - genesis
  #   extends:
  #     service: genesis

  #   build: 
  #     context: ./${FRONTEND_WORKDIR}
  #     dockerfile: ./${FRONTEND_DOCKERFILE}
  #     args:
  #       - BASE_IMG
  #       - FLASK_C_WORKDIR=${FRONTEND_C_WORKDIR}
  #       - FLASK_EXEC_SCRIPT=${FRONTEND_EXEC_SCRIPT}
  #   image: ${FRONTEND_IMG}
  #   ports:
  #     - "${FRONTEND_PORT}:${FRONTEND_PORT}"

  #   hostname: ${FRONTEND_SERVICE}
  #   container_name: ${FRONTEND_SERVICE}

  #   environment:
  #     - SERVICE_NAME=${IMG_GEN_SERVICE}
  #     - PORT=${FRONTEND_PORT}


  #   volumes:
  #     - ./${FRONTEND_WORKDIR}:${FRONTEND_C_WORKDIR}
  
  text_descriptor:
    depends_on:
      - genesis
    extends:
      service: genesis

    build:
      context: ./${TEXT_DESCRIPTOR_WORKDIR}
      dockerfile: ./${TEXT_DESCRIPTOR_DOCKERFILE}
      args:
        - BASE_IMG
        - FLASK_C_WORKDIR=${TEXT_DESCRIPTOR_C_WORKDIR}
        - FLASK_EXEC_SCRIPT=${TEXT_DESCRIPTOR_EXEC_SCRIPT}
    image: ${TEXT_DESCRIPTOR_IMG}
    ports:
      - "${TEXT_DESCRIPTOR_PORT}:${TEXT_DESCRIPTOR_PORT}"

    hostname: ${TEXT_DESCRIPTOR_SERVICE}
    container_name: ${TEXT_DESCRIPTOR_SERVICE}

    environment:
      - SERVICE_NAME=${IMG_GEN_SERVICE}
      - PORT=${TEXT_DESCRIPTOR_PORT}

    volumes:
      - ./${TEXT_DESCRIPTOR_WORKDIR}:${TEXT_DESCRIPTOR_C_WORKDIR}

  # img_uploader:
  #   depends_on:
  #     - genesis
  #   extends:
  #     service: genesis

  #   build: 
  #     context: ./${FRONTEND_WORKDIR}
  #     dockerfile: ./Dockerfile_flask
  #     args:
  #       - BASE_IMG
  #       - FRONTEND_C_WORKDIR
  #       - FRONTEND_EXEC_SCRIPT
  #   image: ${FRONTEND_IMG}
  #   ports:
  #     - "${IMG_UPLOADER_PORT}:${IMG_UPLOADER_PORT}"

  #   hostname: ${FRONTEND_SERVICE}
  #   container_name: ${FRONTEND_SERVICE}

  #   environment:
  #     - SERVICE_NAME=${IMG_GEN_SERVICE}

  #   volumes:
  #     - ./${FRONTEND_WORKDIR}:${FRONTEND_C_WORKDIR}




  # influxdb:
  #   image: ${INFLUX_IMG}

  #   environment:
  #     INFLUXDB_DB: homeassistant
    
  #   ports:
  #     - "$INFLUX_DB_PORT:$INFLUX_DB_PORT"
  #   volumes:
  #     - ./influxdb:/var/lib/influxdb

  #   container_name: ${INFLUX_CONTAINER}
  #   hostname: ${INFLUX_CONTAINER}



# volumes:
#   metrics_publisher:
  # ${PROBE_FOLDER}:
