#https://grafana.com/docs/grafana/latest/datasources/influxdb/#provision-the-data-source
apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    isDefault: true
    uid: "c3c7699e-29c0-41d9-bab2-e354b32ae05f"
    #access: proxy
    #user: grafana
    url: http://influxdb:8086
    jsonData:
      dbName: monitoring
      httpMode: POST
    #secureJsonData:
    #  password: grafana